### ISSUE TITLE
Get cost by latitude/longitude

### ISSUE THREAD

**Issue by nullpntr** [nft/uklon-api#1]
Hey Igor,

Is it possible to get a cost by passing latitude/longitude instead of exact addresses?
Or get an address by latitude/longitude?

Thanks

**Comment by andriikrupka** [comment]
Hello,
Do you have any news about getting cost by lat/long?

**Comment by nullpntr** [comment]
Hello
Not yet

**Comment by nft** [comment]
Hello, actually, I'm not sure that uklon can do that. As far as I know, they don't support lat/long points. I think, they use 3rd party lib, like `google` to get the closest street.
